version: '3'

services:
  database:
    build: .
    environment:
      - POSTGRES_USER=django 
      - POSTGRES_PASSWORD=django 
      - POSTGRES_DB=postgres 
      - USERMAP_UID=999 
      - USERMAP_GID=999
    ports: 
      - "5432:5432" 
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 30s
      retries: 10
      start_period: 30s
  create_tables:
    build: ./create_tables/create_tables/.
    networks:
      - db_network
    links:
      - "database:database"
    depends_on:
      database:
        condition: service_healthy
  app:
    build: ./observer/. 
    ports:
      - "8081:8081"
    links: 
      - "database:database"
    restart: on-failure:5
    depends_on:
      - database
    networks:
      - db_network
networks: 
  db_network:
    driver: bridge
